---
author:
title: "EDAV Fall 2020 PSet 4"
output: html_document
---

EDAV Fall 2020 PSet 4

This assignment is designed to help you get started on the final project. Be sure to review the final project instructions (https://edav.info/project.html).

### 1. The Team

Who's on the team? (Include names and UNIs)

Xiaonan Guo(xg2308), Gaoyi Shi (g32012), Kenny Jin (jj3134), Jiayin Lin (jl5802)

How do you plan to divide up the work? (Grading is on a group basis. The point of asking is to encourage you to think about this and design a plan.)

For each task, we have a leader that organizes the activity, with the rest of team members doing individual contribution. 
	
Github:  lead-contributors  (Xiaonan, Kenny, each person builds his own branch)

Part 1 Data Cleaning (main contributor, 1-50%, 3-50%) (Lead: Kenny Jin)
                      Missing value, duplicates, outliers.
                      
Part 2 Data Transformation (Lead: Xiaonan Guo)
                      Tidy, pivot. prepare for part 3 and part 4
                       Rescaling
                       
Part 3 Data Exploration (Lead: Gaoyi shi)
                      Continuous variables
                      Categorical variables
                      
Part 4 Data Visualization (Lead: Jiayin Lin)
                      Interactive plots
                      
Report (Everyone)

What is your plan for managing the git/GitHub workflow? That is, who will merge pull requests? How will you attempt to avoid conflicts? How will you communicate?

Kenny and Xiaonan will take charge of merging requests. Each of us will create a separate branch, and the leaders will inspect before merging to the main branch. We will enclose clear commit messages when making any requests. Leaders will communicate with each contributor about details. 

### 2. The Questions

List three questions that you hope you will be able to answer from your research.
(It's ok if these change as your work progresses.)

How has COVID-19 affected Citi Bike operations?

How do holidays/ weather/ user profiles affect Citi Bike operations?

Which routes are the most popular among riders?

### 3. GitHub repo

Set up your final project repository following the EDAV project template. Provide the link to the repo.
Make sure that all team members have write access to the repository and have practiced making contributions. Provide a link to the contributors page of your repository showing that all team members have made contributions to the repo (Note that we do not have the ability to see who has write access, only contributors):

https://github.com/ds-eda-viz/final_project_5702
 
### 4. Data Sources

https://www.citibikenyc.com/system-data
It's the open data source which is downloadable from the citi bike official website.
The data files are  stored as csv format and saved monthly.  
It includes the user profile( user id, age, gender, year of birth and user type), trip starting time, starting bike station, ending time, ending bike station, bike id, and trip duration.
We have reviewed the dataset which does not have sensitive data and can be used publicly in our final project.
 
### 5. Data Transformation

After merging all monthly data into one dataset, we will use the 'tidyverse' package to transform our data into long form before we perform any analysis or visualization. In addition, we will rescale and add new attributes if necessary.
We will also double check the dataset to make sure it contains no missing or abnormal values. 

### 6. Missing Values

Check the whole datasets (if contains several tables), figure out features/columns
Understand data type (continuous variables, categorical variables)

Different methods to deal with missing values

-- Remove na (row/columns)

-- Impute: Fillna (mean, mode, infer, backfill, forward fill..)
 